// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.19.4
// source: api/helloworld/v1/book.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBooksRequest) Reset() {
	*x = GetBooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_v1_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksRequest) ProtoMessage() {}

func (x *GetBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksRequest.ProtoReflect.Descriptor instead.
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_book_proto_rawDescGZIP(), []int{0}
}

func (x *GetBooksRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBooksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price   string `protobuf:"bytes,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Author  string `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	Sales   int32  `protobuf:"varint,5,opt,name=Sales,proto3" json:"Sales,omitempty"`
	Stock   int32  `protobuf:"varint,6,opt,name=Stock,proto3" json:"Stock,omitempty"`
	ImaPath string `protobuf:"bytes,7,opt,name=ImaPath,proto3" json:"ImaPath,omitempty"`
}

func (x *GetBooksReply) Reset() {
	*x = GetBooksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_v1_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBooksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksReply) ProtoMessage() {}

func (x *GetBooksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksReply.ProtoReflect.Descriptor instead.
func (*GetBooksReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_book_proto_rawDescGZIP(), []int{1}
}

func (x *GetBooksReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBooksReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBooksReply) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetBooksReply) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetBooksReply) GetSales() int32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *GetBooksReply) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetBooksReply) GetImaPath() string {
	if x != nil {
		return x.ImaPath
	}
	return ""
}

var File_api_helloworld_v1_book_proto protoreflect.FileDescriptor

var file_api_helloworld_v1_book_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x61, 0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0xa7, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6d, 0x61, 0x50, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x49, 0x6d, 0x61, 0x50, 0x61, 0x74, 0x68, 0x32, 0x6b, 0x0a, 0x04,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x63, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x12,
	0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f,
	0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x33, 0x0a, 0x11, 0x61, 0x70, 0x69,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x50, 0x01,
	0x5a, 0x1c, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_helloworld_v1_book_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_book_proto_rawDescData = file_api_helloworld_v1_book_proto_rawDesc
)

func file_api_helloworld_v1_book_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_book_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_helloworld_v1_book_proto_rawDescData)
	})
	return file_api_helloworld_v1_book_proto_rawDescData
}

var file_api_helloworld_v1_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_helloworld_v1_book_proto_goTypes = []interface{}{
	(*GetBooksRequest)(nil), // 0: api.helloworld.v1.GetBooksRequest
	(*GetBooksReply)(nil),   // 1: api.helloworld.v1.GetBooksReply
}
var file_api_helloworld_v1_book_proto_depIdxs = []int32{
	0, // 0: api.helloworld.v1.Book.GetBook:input_type -> api.helloworld.v1.GetBooksRequest
	1, // 1: api.helloworld.v1.Book.GetBook:output_type -> api.helloworld.v1.GetBooksReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_book_proto_init() }
func file_api_helloworld_v1_book_proto_init() {
	if File_api_helloworld_v1_book_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_helloworld_v1_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_v1_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBooksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_helloworld_v1_book_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_book_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_book_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_book_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_book_proto = out.File
	file_api_helloworld_v1_book_proto_rawDesc = nil
	file_api_helloworld_v1_book_proto_goTypes = nil
	file_api_helloworld_v1_book_proto_depIdxs = nil
}
