// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"student/internal/biz"
	"student/internal/conf"
	"student/internal/data"
	"student/internal/server"
	"student/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewGormDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(logger, db)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	studentRepo := data.NewStudentRepo(dataData, logger)
	studentUsecase := biz.NewStudentUsecase(studentRepo, logger)
	studentService := service.NewStudentService(studentUsecase, logger)
	bookRepo := data.NewBookRepo(dataData, logger)
	bookUsecase := biz.NewBookUsecase(bookRepo, logger)
	bookService := service.NewBookService(bookUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, studentService, bookService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, studentService, bookService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
